### PR TITLE
Fix default listSize

### PR DESCRIPTION
**Pull request by rob-ott**
Corrected the default listSize to prevent it from always being overwritten by the DEFAULT_LIST_SIZE as noted in the following issues:
- Fixes JENKINS-66726
- Fixes JENKINS-66719

Code changes:
- Added "String listSize" to the constructor
- Changed the initial set from "this.listSize = DEFAULT_LIST_SIZE" to "this.listSize = listSize"

### CODE REVIEW

**Comment by rob-ott** [comment]
Thank you for merging the pull request. Will this be released soon?

Thanks again!

**Comment by rob-ott** [comment]
Hi @huangsuoyuan,

Will you be creating a release soon that includes this change?

Thanks!

**Comment by huangsuoyuan** [comment]
hi，thank you for this MR!
I tried to release the update but stuck on my Jenkins release account which is valid any more for some reason I do not know
Still work on it with community manager

**Comment by huangsuoyuan** [comment]
@rob-ott the plugin is released. thank you again for your PR!

**Comment by rob-ott** [comment]
That's great and thank you for all your help, @huangsuoyuan!

**Pull request merged**
